on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * *

permissions:
  contents: read

name: Main
jobs:
  windows:
    name: windows ${{matrix.quantum}}${{matrix.hdri_flag}}${{matrix.openmp_flag}} (${{matrix.architecture}})
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        architecture: [ x64 ]
        quantum: [ Q8 ]
        openmp: [ openMP ]
        hdri: [ noHdri, hdri ]
        exclude:
          - quantum: Q8
            hdri: hdri
          - architecture: x86
            openmp: openMP
        include:
          - openmp: openMP
            openmp_flag: '-OpenMP'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          persist-credentials: false

      - name: Update ImageMagick.commit to latest commit
        run: ./update.imagemagick.cmd
        if: github.event_name == 'schedule'
        working-directory: src/ImageMagick

      - name: Clone ImageMagick libraries
        shell: cmd
        run: checkout-release.cmd ${{matrix.architecture}} ${{matrix.openmp}}
        working-directory: src/ImageMagick

      - name: Build
        shell: cmd
        run: build.cmd Release ${{matrix.quantum}} ${{matrix.architecture}} ${{matrix.hdri}} ${{matrix.openmp}}
        working-directory: build/windows

      - name: Copy Resources
        shell: cmd
        run: |
          call copy-resources.cmd ..\..\resources-artifacts
        working-directory: build/windows

      - name: Upload resources
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: resources-${{matrix.quantum}}${{matrix.hdri_flag}}-${{matrix.architecture}}${{matrix.openmp_flag}}
          path: resources-artifacts

      - name: Copy Native
        shell: cmd
        run: |
          call copy-native.cmd ..\..\artifacts Release${{matrix.quantum}}${{matrix.hdri_flag}}${{matrix.openmp_flag}} ${{matrix.architecture}}
        working-directory: build/windows

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: windows-${{matrix.quantum}}${{matrix.hdri_flag}}-${{matrix.architecture}}${{matrix.openmp_flag}}
          path: artifacts
